"""removed unit price association table

Revision ID: d1744d6794d9
Revises: b01c465dace3
Create Date: 2025-12-14 19:32:12.951538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1744d6794d9'
down_revision: Union[str, Sequence[str], None] = 'b01c465dace3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productorder', 'unit_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productorder', sa.Column('unit_price', sa.FLOAT(), nullable=False))
    # ### end Alembic commands ###
